//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Domain.Resources.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ab.
        /// </summary>
        public static string Ab {
            get {
                return ResourceManager.GetString("Ab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string AboutText {
            get {
                return ResourceManager.GetString("AboutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Above.
        /// </summary>
        public static string Above {
            get {
                return ResourceManager.GetString("Above", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Absence Report.
        /// </summary>
        public static string AbsenceReport {
            get {
                return ResourceManager.GetString("AbsenceReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Absence Days.
        /// </summary>
        public static string AbsentDays {
            get {
                return ResourceManager.GetString("AbsentDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred.
        /// </summary>
        public static string AnUnexpectedErrorOccurred {
            get {
                return ResourceManager.GetString("AnUnexpectedErrorOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image File is More Than 3 MG.
        /// </summary>
        public static string ImageFileMore3mg {
            get {
                return ResourceManager.GetString("ImageFileMore3mg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only Image files are allowed.
        /// </summary>
        public static string ImageOnly {
            get {
                return ResourceManager.GetString("ImageOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Page Not Found.
        /// </summary>
        public static string pageNotFound {
            get {
                return ResourceManager.GetString("pageNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pdf File is More Than 5 MG.
        /// </summary>
        public static string pdfFileMore5mg {
            get {
                return ResourceManager.GetString("pdfFileMore5mg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only PDF files are allowed.
        /// </summary>
        public static string PdfOnly {
            get {
                return ResourceManager.GetString("PdfOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return to the previous page.
        /// </summary>
        public static string ReturnBackToPreviousPage {
            get {
                return ResourceManager.GetString("ReturnBackToPreviousPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not authorized to access this page.
        /// </summary>
        public static string YouNotAuthorizedAccessPage {
            get {
                return ResourceManager.GetString("YouNotAuthorizedAccessPage", resourceCulture);
            }
        }
    }
}
