//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource3 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource3() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Domain.Resources.Resource3", typeof(Resource3).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add image.
        /// </summary>
        public static string AddImage {
            get {
                return ResourceManager.GetString("AddImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Signature.
        /// </summary>
        public static string AddSignature {
            get {
                return ResourceManager.GetString("AddSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change image.
        /// </summary>
        public static string ChangeImage {
            get {
                return ResourceManager.GetString("ChangeImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Signature.
        /// </summary>
        public static string ChangeSignature {
            get {
                return ResourceManager.GetString("ChangeSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check.
        /// </summary>
        public static string Check {
            get {
                return ResourceManager.GetString("Check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Discounts &amp; Bonuses Excel.
        /// </summary>
        public static string ExportDiscounts_BonusesExcel {
            get {
                return ResourceManager.GetString("ExportDiscounts_BonusesExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  FUJAIRAH SCIENCE CLUB.
        /// </summary>
        public static string FUJAIRAHSCIENCECLUB {
            get {
                return ResourceManager.GetString("FUJAIRAHSCIENCECLUB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Size 5MB.
        /// </summary>
        public static string MaximumFileSize5MB {
            get {
                return ResourceManager.GetString("MaximumFileSize5MB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to jpg.png 300*270px  | Max Size 3MB.
        /// </summary>
        public static string MaximumImageSize3MB {
            get {
                return ResourceManager.GetString("MaximumImageSize3MB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messages Logs.
        /// </summary>
        public static string MessagesLogs {
            get {
                return ResourceManager.GetString("MessagesLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Information.
        /// </summary>
        public static string PersonalInformation {
            get {
                return ResourceManager.GetString("PersonalInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to title.
        /// </summary>
        public static string reportTitle {
            get {
                return ResourceManager.GetString("reportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Signature.
        /// </summary>
        public static string SaveSignature {
            get {
                return ResourceManager.GetString("SaveSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscribed.
        /// </summary>
        public static string Subscriber {
            get {
                return ResourceManager.GetString("Subscriber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscription.
        /// </summary>
        public static string Subscription {
            get {
                return ResourceManager.GetString("Subscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string test {
            get {
                return ResourceManager.GetString("test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fujairah Scientific Club Data Managment System.
        /// </summary>
        public static string TitleLogin {
            get {
                return ResourceManager.GetString("TitleLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UploadFile PDF.
        /// </summary>
        public static string UploadFilePDF {
            get {
                return ResourceManager.GetString("UploadFilePDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to download file.
        /// </summary>
        public static string ViewFile {
            get {
                return ResourceManager.GetString("ViewFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View image.
        /// </summary>
        public static string ViewImage {
            get {
                return ResourceManager.GetString("ViewImage", resourceCulture);
            }
        }
    }
}
